version: '3.9'

services:
  frontend:
    container_name: frontend_vite
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "npm run dev"
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/home/frontend

  redis:
    container_name: redis
    image: "redis:alpine"

  celery:
    container_name: celery_worker
    build: ./backend
    command: celery -A core worker -l INFO -B
    volumes:
      # - backend_volume:/app
        - ./backend:/home/backend
    depends_on:
      - redis

  backend:
    container_name: backend_django
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      # - backend_volume:/home/backend
        - ./backend:/home/backend

# volumes:
#   backend_volume: