version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "npm run dev"
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/frontend

    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
