# Generated by Django 4.2.7 on 2023-11-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('velocity', models.FloatField()),
                ('timestamp', models.FloatField()),
                ('visibility', models.CharField(max_length=25)),
                ('solar_latitude', models.FloatField()),
                ('solar_longitude', models.FloatField()),
                ('unit', models.CharField(choices=[('km', 'kilometers'), ('mi', 'miles')], max_length=10)),
            ],
        ),
    ]
