# Generated by Django 4.2.7 on 2023-11-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iss', '0002_rename_solar_latitude_iss_solar_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iss',
            old_name='unit',
            new_name='units',
        ),
    ]
